#pragma once
#include <array>
#include <vector>
#include <functional>
#include <cstdint>
#include <utility>

#define NUM_RE_ENTRY_POINTS 376

namespace kbf {

	using EntryPointHandle = uint64_t;
	using EntryCallback = std::function<void()>;

	enum class EntryTiming {
		PRE_FUNCTION,
		POST_FUNCTION
	};

	class EntryPoints {
	public:
		static EntryPoints& instance() {
			static EntryPoints s_instance;
			return s_instance;
		}

		struct Binding {
			EntryCallback callback;
			EntryTiming timing{ EntryTiming::PRE_FUNCTION };
			bool active{ true };
		};

		bool isValid(uint32_t entry, uint32_t binding) const;
		EntryPointHandle addBinding(EntryTiming timing, const char* name, EntryCallback fn, bool active = true);
		void setActive(EntryPointHandle handle, bool active);
		void removeBinding(EntryPointHandle handle);
		void dispatch(int index, EntryTiming timing);
		void dispatch(const char* name, EntryTiming timing);
		std::vector<EntryPointHandle> getActiveHandles(const char* name) const;

		static const std::array<const char*, NUM_RE_ENTRY_POINTS>& getEntryPointNames() { return ENTRY_POINT_NAMES; }

	private:
		EntryPoints() = default;
		~EntryPoints() = default;
		EntryPoints(const EntryPoints&) = delete;
		EntryPoints& operator=(const EntryPoints&) = delete;

		std::array<std::vector<Binding>, NUM_RE_ENTRY_POINTS> m_bindings{};

		// ===== Trampolines =====
		template <size_t Index>
		inline static void PreHookTrampoline() {
			EntryPoints::instance().dispatch(Index, EntryTiming::PRE_FUNCTION);
		}

		template <size_t Index>
		inline static void PostHookTrampoline() {
			EntryPoints::instance().dispatch(Index, EntryTiming::POST_FUNCTION);
		}

		// ===== Tables =====
		template <size_t... Is>
		inline static constexpr auto makePreTable(std::index_sequence<Is...>) {
			return std::array<void(*)(), sizeof...(Is)>{ &PreHookTrampoline<Is>... };
		}

		template <size_t... Is>
		inline static constexpr auto makePostTable(std::index_sequence<Is...>) {
			return std::array<void(*)(), sizeof...(Is)>{ &PostHookTrampoline<Is>... };
		}

	public:
		inline static constexpr auto PRE_HOOKS = makePreTable(std::make_index_sequence<NUM_RE_ENTRY_POINTS>{});
		inline static constexpr auto POST_HOOKS = makePostTable(std::make_index_sequence<NUM_RE_ENTRY_POINTS>{});
		static constexpr EntryPointHandle INVALID_HANDLE = static_cast<EntryPointHandle>(-1);
		static constexpr std::array<const char*, NUM_RE_ENTRY_POINTS> ENTRY_POINT_NAMES{
			"Initialize",
			"InitializeLog",
			"InitializeGameCore",
			"InitializeStorage",
			"InitializeResourceManager",
			"InitializeScene",
			"InitializeRemoteHost",
			"InitializeVM",
			"InitializeSystemService",
			"InitializeHardwareService",
			"InitializePushNotificationService",
			"InitializeDialog",
			"InitializeShareService",
			"InitializeUserService",
			"InitializeUDS",
			"InitializeModalDialogService",
			"InitializeGlobalUserData",
			"InitializeSteam",
			"InitializeWeGame",
			"InitializeXCloud",
			"InitializeRebe",
			"InitializeBcat",
			"InitializeEffectMemorySettings",
			"InitializeRenderer",
			"InitializeVR",
			"InitializeSpeedTree",
			"InitializeHID",
			"InitializeEffect",
			"InitializeGeometry",
			"InitializeLandscape",
			"InitializeHoudini",
			"InitializeSound",
			"InitializeWwiselib",
			"InitializeSimpleWwise",
			"InitializeWwise",
			"InitializeAudioRender",
			"InitializeGUI",
			"InitializeSpine",
			"InitializeMotion",
			"InitializeBehaviorTree",
			"InitializeAutoPlay",
			"InitializeScenario",
			"InitializeOctree",
			"InitializeAreaMap",
			"InitializeFSM",
			"InitializeNavigation",
			"InitializePointGraph",
			"InitializeFluidFlock",
			"InitializeTimeline",
			"InitializePhysics",
			"InitializeDynamics",
			"InitializeHavok",
			"InitializeBake",
			"InitializeNetwork",
			"InitializePuppet",
			"InitializeVoiceChat",
			"InitializeVivoxlib",
			"InitializeStore",
			"InitializeBrowser",
			"InitializeDevelopSystem",
			"InitializeBehavior",
			"InitializeMovie",
			"InitializeMame",
			"InitializeSkuService",
			"InitializeTelemetry",
			"InitializeHansoft",
			"InitializeNNFC",
			"InitializeMixer",
			"InitializeThreadPool",
			"Setup",
			"SetupJobScheduler",
			"SetupResourceManager",
			"SetupStorage",
			"SetupGlobalUserData",
			"SetupScene",
			"SetupDevelopSystem",
			"SetupUserService",
			"SetupSystemService",
			"SetupHardwareService",
			"SetupPushNotificationService",
			"SetupShareService",
			"SetupModalDialogService",
			"SetupVM",
			"SetupHID",
			"SetupRenderer",
			"SetupEffect",
			"SetupGeometry",
			"SetupLandscape",
			"SetupHoudini",
			"SetupSound",
			"SetupWwiselib",
			"SetupSimpleWwise",
			"SetupWwise",
			"SetupAudioRender",
			"SetupMotion",
			"SetupNavigation",
			"SetupPointGraph",
			"SetupPhysics",
			"SetupDynamics",
			"SetupHavok",
			"SetupMovie",
			"SetupMame",
			"SetupNetwork",
			"SetupPuppet",
			"SetupStore",
			"SetupBrowser",
			"SetupVoiceChat",
			"SetupVivoxlib",
			"SetupSkuService",
			"SetupTelemetry",
			"SetupHansoft",
			"StartApp",
			"SetupOctree",
			"SetupAreaMap",
			"SetupBehaviorTree",
			"SetupFSM",
			"SetupGUI",
			"SetupSpine",
			"SetupSpeedTree",
			"SetupNNFC",
			"Start",
			"StartStorage",
			"StartResourceManager",
			"StartGlobalUserData",
			"StartPhysics",
			"StartDynamics",
			"StartGUI",
			"StartTimeline",
			"StartOctree",
			"StartAreaMap",
			"StartBehaviorTree",
			"StartFSM",
			"StartSound",
			"StartWwise",
			"StartAudioRender",
			"StartScene",
			"StartRebe",
			"StartNetwork",
			"Update",
			"UpdateDialog",
			"UpdateRemoteHost",
			"UpdateStorage",
			"UpdateScene",
			"UpdateDevelopSystem",
			"UpdateWidget",
			"UpdateAutoPlay",
			"UpdateScenario",
			"UpdateCapture",
			"BeginFrameRendering",
			"UpdateVR",
			"UpdateHID",
			"UpdateMotionFrame",
			"BeginDynamics",
			"PreupdateGUI",
			"BeginHavok",
			"UpdateAIMap",
			"CreatePreupdateGroupFSM",
			"CreatePreupdateGroupBehaviorTree",
			"UpdateGlobalUserData",
			"UpdateUDS",
			"UpdateUserService",
			"UpdateSystemService",
			"UpdateHardwareService",
			"UpdatePushNotificationService",
			"UpdateShareService",
			"UpdateSteam",
			"UpdateWeGame",
			"UpdateBcat",
			"UpdateXCloud",
			"UpdateRebe",
			"UpdateNNFC",
			"BeginPhysics",
			"BeginUpdatePrimitive",
			"BeginUpdatePrimitiveGUI",
			"BeginUpdateSpineDraw",
			"UpdatePuppet",
			"UpdateGUI",
			"PreupdateBehavior",
			"PreupdateBehaviorTree",
			"PreupdateFSM",
			"PreupdateTimeline",
			"UpdateBehavior",
			"CreateUpdateGroupBehaviorTree",
			"CreateNavigationChain",
			"CreateUpdateGroupFSM",
			"UpdateTimeline",
			"PreUpdateAreaMap",
			"UpdateOctree",
			"UpdateAreaMap",
			"UpdateBehaviorTree",
			"UpdateTimelineFsm2",
			"UpdateNavigationPrev",
			"UpdateFSM",
			"UpdateMotion",
			"UpdateSpine",
			"EffectCollisionLimit",
			"UpdatePhysicsAfterUpdatePhase",
			"UpdateGeometry",
			"UpdateLandscape",
			"UpdateHoudini",
			"UpdatePhysicsCharacterController",
			"BeginUpdateHavok2",
			"UpdateDynamics",
			"UpdateNavigation",
			"UpdatePointGraph",
			"UpdateFluidFlock",
			"UpdateConstraintsBegin",
			"LateUpdateBehavior",
			"EditUpdateBehavior",
			"LateUpdateSpine",
			"BeginUpdateHavok",
			"BeginUpdateEffect",
			"UpdateConstraintsEnd",
			"UpdatePhysicsAfterLateUpdatePhase",
			"PrerenderGUI",
			"PrepareRendering",
			"UpdateSound",
			"UpdateWwiselib",
			"UpdateSimpleWwise",
			"UpdateWwise",
			"UpdateAudioRender",
			"CreateSelectorGroupFSM",
			"UpdateNetwork",
			"UpdateHavok",
			"EndUpdateHavok",
			"UpdateFSMSelector",
			"UpdateBehaviorTreeSelector",
			"BeforeLockSceneRendering",
			"EndUpdateHavok2",
			"UpdateJointExpression",
			"UpdateBehaviorTreeSelectorLegacy",
			"UpdateEffect",
			"EndUpdateEffect",
			"UpdateWidgetDynamics",
			"LockScene",
			"WaitRendering",
			"EndDynamics",
			"EndPhysics",
			"BeginRendering",
			"UpdateSpeedTree",
			"RenderDynamics",
			"RenderGUI",
			"RenderGeometry",
			"RenderLandscape",
			"RenderHoudini",
			"UpdatePrimitiveGUI",
			"UpdatePrimitive",
			"UpdateSpineDraw",
			"EndUpdatePrimitive",
			"EndUpdatePrimitiveGUI",
			"EndUpdateSpineDraw",
			"GUIPostPrimitiveRender",
			"ShapeRenderer",
			"UpdateMovie",
			"UpdateMame",
			"UpdateTelemetry",
			"UpdateHansoft",
			"DrawWidget",
			"DevelopRenderer",
			"EndRendering",
			"UpdateStore",
			"UpdateBrowser",
			"UpdateVoiceChat",
			"UpdateVivoxlib",
			"UnlockScene",
			"UpdateVM",
			"StepVisualDebugger",
			"WaitForVblank",
			"Terminate",
			"TerminateScene",
			"TerminateRemoteHost",
			"TerminateHansoft",
			"TerminateTelemetry",
			"TerminateMame",
			"TerminateMovie",
			"TerminateSound",
			"TerminateSimpleWwise",
			"TerminateWwise",
			"TerminateWwiselib",
			"TerminateAudioRender",
			"TerminateVoiceChat",
			"TerminateVivoxlib",
			"TerminatePuppet",
			"TerminateNetwork",
			"TerminateStore",
			"TerminateBrowser",
			"TerminateSpine",
			"TerminateGUI",
			"TerminateAreaMap",
			"TerminateOctree",
			"TerminateFluidFlock",
			"TerminateBehaviorTree",
			"TerminateFSM",
			"TerminateNavigation",
			"TerminatePointGraph",
			"TerminateEffect",
			"TerminateGeometry",
			"TerminateLandscape",
			"TerminateHoudini",
			"TerminateRenderer",
			"TerminateHID",
			"TerminateDynamics",
			"TerminatePhysics",
			"TerminateResourceManager",
			"TerminateHavok",
			"TerminateModalDialogService",
			"TerminateShareService",
			"TerminateGlobalUserData",
			"TerminateStorage",
			"TerminateVM",
			"TerminateJobScheduler",
			"Finalize",
			"FinalizeThreadPool",
			"FinalizeHansoft",
			"FinalizeTelemetry",
			"FinalizeMame",
			"FinalizeMovie",
			"FinalizeBehavior",
			"FinalizeDevelopSystem",
			"FinalizeTimeline",
			"FinalizePuppet",
			"FinalizeNetwork",
			"FinalizeStore",
			"FinalizeBrowser",
			"finalizeAutoPlay",
			"finalizeScenario",
			"FinalizeBehaviorTree",
			"FinalizeFSM",
			"FinalizeNavigation",
			"FinalizePointGraph",
			"FinalizeAreaMap",
			"FinalizeOctree",
			"FinalizeFluidFlock",
			"FinalizeMotion",
			"FinalizeDynamics",
			"FinalizePhysics",
			"FinalizeHavok",
			"FinalizeBake",
			"FinalizeSpine",
			"FinalizeGUI",
			"FinalizeSound",
			"FinalizeWwiselib",
			"FinalizeSimpleWwise",
			"FinalizeWwise",
			"FinalizeAudioRender",
			"FinalizeEffect",
			"FinalizeGeometry",
			"FinalizeSpeedTree",
			"FinalizeLandscape",
			"FinalizeHoudini",
			"FinalizeRenderer",
			"FinalizeHID",
			"FinalizeVR",
			"FinalizeBcat",
			"FinalizeRebe",
			"FinalizeXCloud",
			"FinalizeSteam",
			"FinalizeWeGame",
			"FinalizeNNFC",
			"FinalizeGlobalUserData",
			"FinalizeModalDialogService",
			"FinalizeSkuService",
			"FinalizeUDS",
			"FinalizeUserService",
			"FinalizeShareService",
			"FinalizeSystemService",
			"FinalizeHardwareService",
			"FinalizePushNotificationService",
			"FinalizeScene",
			"FinalizeVM",
			"FinalizeResourceManager",
			"FinalizeRemoteHost",
			"FinalizeStorage",
			"FinalizeDialog",
			"FinalizeMixer",
			"FinalizeGameCore"
		};
	};

}