name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out this bug report as completely as possible. Thanks!
  - type: input
    id: describe_bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I noticed that ...
  - type: dropdown
    id: crash
    attributes:
      label: Does this bug cause a game crash?
      description: Select Yes or No
      options:
        - "Yes"
        - "No"
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1.
        2.
        3.
        4.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: I expected that ...
  - type: textarea
    id: ref_log
    attributes:
      label: REFramework Log
      description: This log can be found at <Game Directory>/re2_framework_log.txt
      placeholder: Paste or attach re2_framework_log.txt here...
  - type: textarea
    id: kbf_log
    attributes:
      label: KBFs Debug Log (Optional)
      description: This log can copied by going to Debug > Log ingame.
      placeholder: Paste here...
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the problem
      placeholder: Optional
